export type JourneyChapter =
  | "india"
  | "southeast-asia"
  | "east-asia"
  | "australia"
  | "europe";

export type JourneyCountry = {
  order: number;
  slug: string;
  name: string;
  iso3: string;
  displayAnchor: [longitude: number, latitude: number];
  chapter: JourneyChapter;
  featured: boolean;
  coverImage: string;
  coverAlt: string;
  summary: string;
  lesson?: string;
  whoHelped?: string;
  kindnessStory?: string;
  challengeStory?: string;
  videoUrl?: string;
  gallery: Array<{ src: string; alt: string }>;
};

export const journeyCountries: JourneyCountry[] = [
  {
    order: 1,
    slug: "india",
    name: "India",
    iso3: "IND",
    displayAnchor: [78.9629, 20.5937],
    chapter: "india",
    featured: false,
    coverImage: "/media/journey/india/cover.jpg",
    coverAlt: "TODO_OWNER_APPROVAL",
    summary: "TODO_OWNER_APPROVAL",
    kindnessStory: "TODO_OWNER_APPROVAL",
    gallery: [],
  },
  {
    order: 2,
    slug: "sri-lanka",
    name: "Sri Lanka",
    iso3: "LKA",
    displayAnchor: [80.7718, 7.8731],
    chapter: "southeast-asia",
    featured: true,
    coverImage: "/media/journey/sri-lanka/cover.jpg",
    coverAlt: "TODO_OWNER_APPROVAL",
    summary: "The elephant escape.",
    challengeStory: "TODO_OWNER_APPROVAL",
    whoHelped: "TODO_OWNER_APPROVAL",
    lesson: "TODO_OWNER_APPROVAL",
    gallery: [],
  },
  {
    order: 3,
    slug: "vietnam",
    name: "Vietnam",
    iso3: "VNM",
    displayAnchor: [108.2772, 14.0583],
    chapter: "southeast-asia",
    featured: false,
    coverImage: "/media/journey/vietnam/cover.jpg",
    coverAlt: "TODO_OWNER_APPROVAL",
    summary: "TODO_OWNER_APPROVAL",
    kindnessStory: "TODO_OWNER_APPROVAL",
    gallery: [],
  },
  {
    order: 4,
    slug: "cambodia",
    name: "Cambodia",
    iso3: "KHM",
    displayAnchor: [104.991, 12.5657],
    chapter: "southeast-asia",
    featured: false,
    coverImage: "/media/journey/cambodia/cover.jpg",
    coverAlt: "TODO_OWNER_APPROVAL",
    summary: "TODO_OWNER_APPROVAL",
    gallery: [],
  },
  {
    order: 5,
    slug: "thailand",
    name: "Thailand",
    iso3: "THA",
    displayAnchor: [100.9925, 15.87],
    chapter: "southeast-asia",
    featured: true,
    coverImage: "/media/journey/thailand/cover.jpg",
    coverAlt: "TODO_OWNER_APPROVAL",
    summary: "When only Rs 150 remained.",
    challengeStory: "TODO_OWNER_APPROVAL",
    whoHelped: "TODO_OWNER_APPROVAL",
    lesson: "TODO_OWNER_APPROVAL",
    gallery: [],
  },
  {
    order: 6,
    slug: "malaysia",
    name: "Malaysia",
    iso3: "MYS",
    displayAnchor: [101.9758, 4.2105],
    chapter: "southeast-asia",
    featured: false,
    coverImage: "/media/journey/malaysia/cover.jpg",
    coverAlt: "TODO_OWNER_APPROVAL",
    summary: "TODO_OWNER_APPROVAL",
    kindnessStory: "TODO_OWNER_APPROVAL",
    gallery: [],
  },
  {
    order: 7,
    slug: "singapore",
    name: "Singapore",
    iso3: "SGP",
    displayAnchor: [103.8198, 1.3521],
    chapter: "southeast-asia",
    featured: false,
    coverImage: "/media/journey/singapore/cover.jpg",
    coverAlt: "TODO_OWNER_APPROVAL",
    summary: "TODO_OWNER_APPROVAL",
    gallery: [],
  },
  {
    order: 8,
    slug: "indonesia",
    name: "Indonesia",
    iso3: "IDN",
    displayAnchor: [113.9213, -0.7893],
    chapter: "southeast-asia",
    featured: false,
    coverImage: "/media/journey/indonesia/cover.jpg",
    coverAlt: "TODO_OWNER_APPROVAL",
    summary: "TODO_OWNER_APPROVAL",
    challengeStory: "TODO_OWNER_APPROVAL",
    gallery: [],
  },
  {
    order: 9,
    slug: "china",
    name: "China",
    iso3: "CHN",
    displayAnchor: [104.1954, 35.8617],
    chapter: "east-asia",
    featured: false,
    coverImage: "/media/journey/china/cover.jpg",
    coverAlt: "TODO_OWNER_APPROVAL",
    summary: "TODO_OWNER_APPROVAL",
    gallery: [],
  },
  {
    order: 10,
    slug: "japan",
    name: "Japan",
    iso3: "JPN",
    displayAnchor: [138.2529, 36.2048],
    chapter: "east-asia",
    featured: false,
    coverImage: "/media/journey/japan/cover.jpg",
    coverAlt: "TODO_OWNER_APPROVAL",
    summary: "TODO_OWNER_APPROVAL",
    gallery: [],
  },
  {
    order: 11,
    slug: "south-korea",
    name: "South Korea",
    iso3: "KOR",
    displayAnchor: [127.7669, 35.9078],
    chapter: "east-asia",
    featured: false,
    coverImage: "/media/journey/south-korea/cover.jpg",
    coverAlt: "Ranjith standing with his loaded bicycle beneath cherry blossom trees in South Korea",
    summary: "TODO_OWNER_APPROVAL",
    kindnessStory: "TODO_OWNER_APPROVAL",
    gallery: [],
  },
  {
    order: 12,
    slug: "taiwan",
    name: "Taiwan",
    iso3: "TWN",
    displayAnchor: [120.9605, 23.6978],
    chapter: "east-asia",
    featured: false,
    coverImage: "/media/journey/taiwan/cover.jpg",
    coverAlt: "TODO_OWNER_APPROVAL",
    summary: "TODO_OWNER_APPROVAL",
    gallery: [],
  },
  {
    order: 13,
    slug: "mongolia",
    name: "Mongolia",
    iso3: "MNG",
    displayAnchor: [103.8467, 46.8625],
    chapter: "east-asia",
    featured: false,
    coverImage: "/media/journey/mongolia/cover.jpg",
    coverAlt: "TODO_OWNER_APPROVAL",
    summary: "TODO_OWNER_APPROVAL",
    challengeStory: "TODO_OWNER_APPROVAL",
    gallery: [],
  },
  {
    order: 14,
    slug: "australia",
    name: "Australia",
    iso3: "AUS",
    displayAnchor: [133.7751, -25.2744],
    chapter: "australia",
    featured: true,
    coverImage: "/media/journey/australia/cover.jpg",
    coverAlt: "TODO_OWNER_APPROVAL",
    summary: "Two rejections, one destination.",
    kindnessStory: "TODO_OWNER_APPROVAL",
    challengeStory: "TODO_OWNER_APPROVAL",
    whoHelped: "TODO_OWNER_APPROVAL",
    lesson: "TODO_OWNER_APPROVAL",
    gallery: [],
  },
  {
    order: 15,
    slug: "france",
    name: "France",
    iso3: "FRA",
    displayAnchor: [2.2137, 46.2276],
    chapter: "europe",
    featured: false,
    coverImage: "/media/journey/france/cover.jpg",
    coverAlt: "TODO_OWNER_APPROVAL",
    summary: "TODO_OWNER_APPROVAL",
    gallery: [],
  },
  {
    order: 16,
    slug: "switzerland",
    name: "Switzerland",
    iso3: "CHE",
    displayAnchor: [8.2275, 46.8182],
    chapter: "europe",
    featured: false,
    coverImage: "/media/journey/switzerland/cover.jpg",
    coverAlt: "TODO_OWNER_APPROVAL",
    summary: "TODO_OWNER_APPROVAL",
    gallery: [],
  },
  {
    order: 17,
    slug: "germany",
    name: "Germany",
    iso3: "DEU",
    displayAnchor: [10.4515, 51.1657],
    chapter: "europe",
    featured: false,
    coverImage: "/media/journey/germany/cover.jpg",
    coverAlt: "TODO_OWNER_APPROVAL",
    summary: "TODO_OWNER_APPROVAL",
    gallery: [],
  },
  {
    order: 18,
    slug: "austria",
    name: "Austria",
    iso3: "AUT",
    displayAnchor: [14.5501, 47.5162],
    chapter: "europe",
    featured: false,
    coverImage: "/media/journey/austria/cover.jpg",
    coverAlt: "TODO_OWNER_APPROVAL",
    summary: "TODO_OWNER_APPROVAL",
    gallery: [],
  },
  {
    order: 19,
    slug: "italy",
    name: "Italy",
    iso3: "ITA",
    displayAnchor: [12.5674, 41.8719],
    chapter: "europe",
    featured: false,
    coverImage: "/media/journey/italy/cover.jpg",
    coverAlt: "TODO_OWNER_APPROVAL",
    summary: "TODO_OWNER_APPROVAL",
    gallery: [],
  },
  {
    order: 20,
    slug: "slovenia",
    name: "Slovenia",
    iso3: "SVN",
    displayAnchor: [14.9955, 46.1512],
    chapter: "europe",
    featured: false,
    coverImage: "/media/journey/slovenia/cover.jpg",
    coverAlt: "TODO_OWNER_APPROVAL",
    summary: "TODO_OWNER_APPROVAL",
    gallery: [],
  },
  {
    order: 21,
    slug: "croatia",
    name: "Croatia",
    iso3: "HRV",
    displayAnchor: [15.2, 45.1],
    chapter: "europe",
    featured: false,
    coverImage: "/media/journey/croatia/cover.jpg",
    coverAlt: "TODO_OWNER_APPROVAL",
    summary: "TODO_OWNER_APPROVAL",
    gallery: [],
  },
  {
    order: 22,
    slug: "hungary",
    name: "Hungary",
    iso3: "HUN",
    displayAnchor: [19.5033, 47.1625],
    chapter: "europe",
    featured: false,
    coverImage: "/media/journey/hungary/cover.jpg",
    coverAlt: "TODO_OWNER_APPROVAL",
    summary: "TODO_OWNER_APPROVAL",
    gallery: [],
  },
  {
    order: 23,
    slug: "slovakia",
    name: "Slovakia",
    iso3: "SVK",
    displayAnchor: [19.699, 48.669],
    chapter: "europe",
    featured: false,
    coverImage: "/media/journey/slovakia/cover.jpg",
    coverAlt: "TODO_OWNER_APPROVAL",
    summary: "TODO_OWNER_APPROVAL",
    gallery: [],
  },
];
